encryptor/urls.py
from django.urls import path

from . import views

app_name = 'encryptor'

urlpatterns = [
	path('', views.index, name='index'),
	path('decrypt/', views.decrypt, name='decrypt'),
]

new_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('encryptor/', include('encryptor.urls')),
    path('admin/', admin.site.urls),
]

encryptor/models.py
from django.db import models

# Create your models here.

encryptor/views.py
from django.shortcuts import render
from . import aes_encryptor

# Create your views here.
def index(request):
	password = request.GET.get("pass")
	message = request.GET.get("message")
	if password and message:
		encrypted = aes_encryptor.encrypt(message, password)
		return render(request, 'encryptor/index.html', {
			'password': password,
			'message': message,
			'encrypted': encrypted
		})
	return render(request, 'encryptor/index.html', {
		'test': 'test'
	})

def decrypt(request):
	password = request.GET.get("pass")
	message = request.GET.get("message")
	if password and message:
		decrypted = aes_encryptor.decrypt(message, password)
		return render(request, 'encryptor/decrypt.html', {
			'password': password,
			'message': message,
			'decrypted': decrypted
		})
	return render(request, 'encryptor/decrypt.html', {
		'test': 'test'
	})

encryptor/templates/encryptor/decrypt.html
<div class="container">
	<div class="row">
		<form class="form-horizontal" role ="decrypt" method="GET" action="{% url 'encryptor:decrypt' %}">
			<div class="form-group">
          		<label for="pass" class="col-sm-2 control-label">Pass:
          		</label>
          		<div class="col-sm-10">
            		<input type="text" class="form-control" name="pass" 
                  value="{{ request.GET.pass }}" >
         	 	</div>  
        	</div>
        	<div class="form-group">  
          		<label for="message" class="col-sm-2 control-label">Encrypted:</label>
        		<div class="col-sm-10">  
          		<textarea type="text" class="form-control" rows="8" 
          		name="message">{{ request.GET.message }}</textarea>
          		</div>
        	</div>
        	<div class="form-group">
          		<div class="col-sm-offset-2 col-sm-10">
            		<button type="submit" class="btn btn-default">Decrypt</button>
          		</div>       
        	</div>  
		</form>
	</div>
	{% if decrypted %}
    <div class="row">
      <label for="decrypted" class="col-sm-2 control-label">Decrypted:</label>
          <div class="col-sm-10">  
            <textarea type="text" class="form-control" rows="8" 
            name="decrypted">{{ decrypted }}</textarea>
          </div>
    </div>
  {% endif %}
</div>

encryptor/templates/encryptor/index.html
<div class="container">
	<div class="row">
		<form class="form-horizontal" role ="encrypt" method="GET" action="{% url 'encryptor:index' %}">
			<div class="form-group">
          		<label for="pass" class="col-sm-2 control-label">Pass:
          		</label>
          		<div class="col-sm-10">
            		<input type="text" class="form-control" name="pass" 
                  value="{{ request.GET.pass }}" >
         	 	</div>  
        	</div>
        	<div class="form-group">  
          		<label for="message" class="col-sm-2 control-label">Plaintext:</label>
        		<div class="col-sm-10">  
          		<textarea type="text" class="form-control" rows="8" 
          		name="message">{{ request.GET.message }}</textarea>
          		</div>
        	</div>
        	<div class="form-group">
          		<div class="col-sm-offset-2 col-sm-10">
            		<button type="submit" class="btn btn-default">Encrypt</button>
          		</div>       
        	</div>  
		</form>
	</div>
	{% if encrypted %}
    <div class="row">
      <label for="encrypted" class="col-sm-2 control-label">Encrypted:</label>
          <div class="col-sm-10">  
            <textarea type="text" class="form-control" rows="8" 
            name="encrypted">{{ encrypted }}</textarea>
          </div>
    </div>
  {% endif %}
</div>